"""
Builds src/Pane in Release and stages its output into pane/_native/, where
_bootstrap.py looks for a bundled native build first (see its docstring).
This is what turns the pane-ui *source* checkout into something `python -m
build` can package into a wheel that works after `pip install` alone, with
no separate `dotnet build` step required by the end user.

Run from the python/ directory (or anywhere - paths below are relative to
this file, not the current working directory):

    python build_native.py
    python -m build      # produces dist/*.whl and dist/*.tar.gz
    twine upload dist/*  # requires your own PyPI credentials

pane/_native/ is .gitignore'd - it's a build artifact, not source, and gets
regenerated by this script whenever you're about to package a release.
"""

import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PANE_CSPROJ = REPO_ROOT / "src" / "Pane" / "Pane.csproj"
BUILD_OUTPUT = REPO_ROOT / "src" / "Pane" / "bin" / "Release" / "net8.0-windows"
NATIVE_DIR = Path(__file__).resolve().parent / "pane" / "_native"


def main():
    if sys.platform != "win32":
        sys.exit("build_native.py must run on Windows - it invokes `dotnet build` "
                 "for a net8.0-windows/WPF target.")

    print(f"Building {PANE_CSPROJ} (Release)...", flush=True)
    # GenerateRuntimeConfigurationFiles=true: Pane.csproj is a class library,
    # so it doesn't get a runtimeconfig.json by default (only executables
    # normally need one) - but pythonnet's coreclr host needs exactly that
    # file to know to load the Microsoft.WindowsDesktop.App shared framework
    # WPF requires. Forcing it here is cheaper than maintaining a second,
    # redundant "hosting" project just to produce one.
    subprocess.run(
        [
            "dotnet", "build", str(PANE_CSPROJ),
            "-c", "Release",
            "-p:GenerateRuntimeConfigurationFiles=true",
            "-v:minimal",
        ],
        check=True,
    )

    dll = BUILD_OUTPUT / "Pane.dll"
    runtimeconfig = BUILD_OUTPUT / "Pane.runtimeconfig.json"
    for f in (dll, runtimeconfig):
        if not f.exists():
            sys.exit(f"Expected build output missing: {f}")

    NATIVE_DIR.mkdir(parents=True, exist_ok=True)
    for f in (dll, runtimeconfig):
        shutil.copy2(f, NATIVE_DIR / f.name)

    print(f"Staged {dll.name} and {runtimeconfig.name} into {NATIVE_DIR}")


if __name__ == "__main__":
    main()
